wltnthss/jcticket

.idea/encodings.xml, README.md, pom.xml, src/main/java/com/jcticket/example/controller/exampleController.java, src/main/java/com/jcticket/example/dao/exampleDao.java, src/main/java/com/jcticket/example/dao/exampleDaoImpl.java, src/main/java/com/jcticket/example/dto/exampleDto.java, src/main/java/com/jcticket/example/service/exampleService.java, src/main/java/com/my/HomeController.java, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/views/example.jsp, src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/WEB-INF/views/lombok.jsp, src/main/webapp/resources/css/example/example.css, src/main/webapp/resources/sample.css
=> Initial Project 세팅

src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/notice/notice.jsp, src/test/java/com/jcticket/example/dao/exampleDaoImplTest.java
=> mysql 설정 변경, JUNIT 에러해결

src/main/java/com/jcticket/notice/controller/noticeController.java, src/main/webapp/WEB-INF/views/common/footer.jsp, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/notice/notice.jsp, src/main/webapp/resources/css/components/footer.css, src/main/webapp/resources/css/components/header.css, src/main/webapp/resources/css/notice/notice.css, src/test/java/com/jcticket/example/dao/exampleDaoImplTest.java
=> notice layout && notice icon add

src/main/webapp/WEB-INF/views/customercenter/customercenter.jsp
=> customer jsp create

.idea/.gitignore, .idea/encodings.xml, .idea/misc.xml, .idea/sqldialects.xml, src/main/webapp/WEB-INF/views/view/view.jsp
=> view change

.idea/misc.xml, .idea/sqldialects.xml, src/main/java/com/jcticket/notice/dao/NoticeDao.java, src/main/java/com/jcticket/notice/dao/NoticeDaoImpl.java, src/main/resources/mybatis/mapper/notice/noticeMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/test/java/com/jcticket/notice/dao/NoticeDaoImplTest.java
=> notice db 연결 확인

src/main/webapp/WEB-INF/views/common/footer.jsp, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/notice/notice.jsp, src/main/webapp/WEB-INF/views/notice/noticedetail.jsp
=> img 파일 경로 변경

.gitignore
=> gitignore 파일 추가

src/main/java/com/jcticket/login/controller/LoginController.java, src/main/java/com/jcticket/signup/controller/SignUpController.java, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/login.jsp, src/main/webapp/WEB-INF/views/signup/signup.jsp, src/main/webapp/resources/css/login/login.css
=> 회원 로그인 유효성 검사 완

src/main/java/com/jcticket/admin/controller/AdminController.java
user controller index GetMapping 충돌 오류 해결
=> controller 충돌 오류 해결

.gitignore, src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/webapp/WEB-INF/views/admin/adminagency.jsp, src/main/webapp/WEB-INF/views/admin/admincoupon.jsp, src/main/webapp/WEB-INF/views/admin/admindashboard.jsp, src/main/webapp/WEB-INF/views/admin/adminheader.jsp, src/main/webapp/WEB-INF/views/admin/admininquiry.jsp, src/main/webapp/WEB-INF/views/admin/adminnotice.jsp, src/main/webapp/WEB-INF/views/admin/adminproduct.jsp, src/main/webapp/WEB-INF/views/admin/adminsetting.jsp, src/main/webapp/WEB-INF/views/admin/adminstactics.jsp, src/main/webapp/WEB-INF/views/admin/adminuser.jsp, src/main/webapp/resources/css/admin/admin.css, src/main/webapp/resources/css/admin/adminheader.css
=> admin nav layout add

src/main/webapp/resources/css/viewdetail/jquery-ui.css, src/main/webapp/resources/css/viewdetail/viewdetail.css, src/main/webapp/resources/js/viewdetail/viewdetail.js
=> 리뷰전 푸쉬 등록한 날짜만 선택가능까지 구현

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/admin/dto/UserPageDto.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/java/com/jcticket/notice/controller/NoticeController.java, src/main/java/com/my/HomeController.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/resources/mybatis/mybatis-config.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/admin/adminnav.jsp, src/main/webapp/WEB-INF/views/admin/adminuser.jsp, src/main/webapp/WEB-INF/web.xml, src/main/webapp/resources/css/admin/admin.css, src/test/java/com/jcticket/admin/dao/AdminDaoImplTest.java, src/test/java/com/jcticket/notice/dao/NoticeDaoImplTest.java
=> 관리자 회원관리 조회 기능 완료

src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/ticketing/dto/TicketingDto.java, src/main/java/com/jcticket/user/dto/UserDto.java, src/main/webapp/WEB-INF/views/admin/adminuser.jsp, src/test/java/com/jcticket/admin/dao/AdminDaoImplTest.java, src/test/java/com/jcticket/ticketing/dao/TicketingDaoImplTest.java
=> test 삭제 및 티케팅 DTO DB 동기화

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/webapp/WEB-INF/views/admin/adminuser.jsp, src/main/webapp/WEB-INF/views/admin/adminuserdelete.jsp, src/main/webapp/WEB-INF/views/admin/adminuserregister.jsp, src/main/webapp/resources/css/admin/admin.css, src/main/webapp/resources/js/admin/admin.js, src/test/java/com/jcticket/admin/dao/AdminDaoImplTest.java
=> 관리자 회원 등록 기능 구현 완료

src/main/java/com/jcticket/signup/controller/SignUpController.java, src/main/java/com/jcticket/signup/dao/TermsDao.java, src/main/java/com/jcticket/signup/dao/TermsDaoImpl.java, src/main/java/com/jcticket/signup/dto/TermsDto.java, src/main/java/com/jcticket/signup/service/TermsService.java, src/main/java/com/jcticket/signup/service/TermsServiceImpl.java, src/main/java/com/jcticket/user/controller/LoginController.java, src/main/resources/mybatis/mapper/signup/signupMapper.xml, src/main/resources/mybatis/mapper/signup/termsMapper.xml, src/main/resources/mybatis/mybatis-config.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/signup/signup.jsp, src/main/webapp/resources/css/signup/signup.css, src/main/webapp/resources/js/signup/signup.js, src/test/java/com/jcticket/signup/dao/TermsDaoImplTest.java
회원가입 기능 1차적으로 완료 했습니다. 
주석과 설명이 부족한 것 같아서 1차 PR후 내일 한번더 PR날리겠습니다.
=> 회원가입 1차 완료

src/main/java/com/jcticket/signup/controller/SignUpController.java, src/main/java/com/jcticket/signup/dao/SignupDao.java, src/main/java/com/jcticket/signup/dao/SignupDaoImpl.java, src/main/java/com/jcticket/signup/dao/TermsDao.java, src/main/java/com/jcticket/signup/dao/TermsDaoImpl.java, src/main/java/com/jcticket/signup/dto/SignupDto.java, src/main/java/com/jcticket/signup/dto/TermsDto.java, src/main/java/com/jcticket/signup/service/SignupService.java, src/main/java/com/jcticket/signup/service/SignupServiceImpl.java, src/main/java/com/jcticket/signup/service/TermsService.java, src/main/java/com/jcticket/signup/service/TermsServiceImpl.java, src/main/java/com/jcticket/user/controller/LoginController.java, src/main/java/com/jcticket/user/dao/LoginDao.java, src/main/java/com/jcticket/user/dao/LoginDaoImpl.java, src/main/java/com/jcticket/user/service/LoginService.java, src/main/java/com/jcticket/user/service/LoginServiceImpl.java, src/main/resources/mybatis/mapper/signup/signupMapper.xml, src/main/resources/mybatis/mapper/signup/termsMapper.xml, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/login/login.jsp, src/main/webapp/WEB-INF/views/signup/signup.jsp, src/main/webapp/resources/css/components/header.css, src/main/webapp/resources/js/signup/signup.js, src/test/java/com/jcticket/user/dao/LoginDaoImplTest.java
=> 로그아웃, 주석 완료

src/main/java/com/jcticket/viewdetail/controller/ViewController.java, src/main/java/com/jcticket/viewdetail/dao/ViewDetailDao.java, src/main/java/com/jcticket/viewdetail/dao/ViewDetailDaoImpl.java, src/main/java/com/jcticket/viewdetail/service/ViewDetailService.java, src/main/java/com/jcticket/viewdetail/service/ViewDetailServiceImpl.java, src/main/resources/mybatis/mapper/viewdetail/viewdetailMapper.xml, src/main/webapp/WEB-INF/views/viewdetail/viewdetail.jsp, src/main/webapp/resources/js/viewdetail/viewdetail.js
=> DB 공연날짜/DatePicker 연동완료

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/notice/dao/NoticeDao.java, src/main/java/com/jcticket/notice/dao/NoticeDaoImpl.java, src/main/java/com/jcticket/notice/service/NoticeService.java, src/main/java/com/jcticket/notice/service/NoticeServiceImpl.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/resources/mybatis/mapper/notice/noticeMapper.xml, src/main/webapp/WEB-INF/views/admin/adminuserdelete.jsp, src/main/webapp/resources/js/admin/admin.js, src/test/java/com/jcticket/admin/service/AdminServiceImplTest.java, src/test/java/com/jcticket/notice/dao/NoticeDaoImplTest.java, src/test/java/com/jcticket/notice/service/NoticeServiceImplTest.java
=> 코드 리팩토링, 공지사항 테스트 변경

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/test/java/com/jcticket/admin/dao/AdminDaoImplTest.java, src/test/java/com/jcticket/admin/service/AdminServiceImplTest.java
=> 관리자 회원관리 테스트케이스 작성

src/main/java/com/jcticket/viewdetail/controller/ViewController.java, src/main/java/com/jcticket/viewdetail/dao/ViewDetailDao.java, src/main/java/com/jcticket/viewdetail/dao/ViewDetailDaoImpl.java, src/main/java/com/jcticket/viewdetail/dto/JoinDto.java, src/main/java/com/jcticket/viewdetail/service/ViewDetailService.java, src/main/java/com/jcticket/viewdetail/service/ViewDetailServiceImpl.java, src/main/resources/mybatis/mapper/viewdetail/viewdetailMapper.xml, src/main/webapp/WEB-INF/views/viewdetail/viewdetail.jsp, src/test/java/com/jcticket/viewdetail/dao/ViewDetailDaoTest.java
상세보기 링크 http://localhost:8080/test 입니다
mapper.xml viewdetail() 쿼리 수정함
=> 상세보기 링크 http://localhost:8080/test 입니다

src/main/java/com/jcticket/viewdetail/controller/ViewController.java, src/main/java/com/jcticket/viewdetail/dao/ViewDetailDao.java, src/main/java/com/jcticket/viewdetail/dao/ViewDetailDaoImpl.java, src/main/java/com/jcticket/viewdetail/dto/JoinDto.java, src/main/java/com/jcticket/viewdetail/service/ViewDetailService.java, src/main/java/com/jcticket/viewdetail/service/ViewDetailServiceImpl.java, src/main/resources/mybatis/mapper/viewdetail/viewdetailMapper.xml, src/main/webapp/WEB-INF/views/viewdetail/viewdetail.jsp, src/test/java/com/jcticket/viewdetail/dao/ViewDetailDaoTest.java
=> 상세정보 수정사항 반영

src/main/webapp/resources/js/viewdetail/viewdetail.js
=> 상세보기 > 티켓팅 스크립트 조건추가

.idea/webContexts.xml, pom.xml, src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/java/com/jcticket/agency/dto/AgencyDto.java, src/main/java/com/jcticket/common/CommonValidateHandling.java, src/main/java/com/jcticket/user/dto/UserDto.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/admin/adminagencyregister.jsp, src/main/webapp/WEB-INF/views/admin/adminuserregister.jsp, src/test/java/com/jcticket/admin/dao/AdminDaoImplTest.java
=> 회원, 기획사 @Validate 어노테이션 적용

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/admin/dto/PageDto.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/java/com/jcticket/agency/dto/AgencyDto.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/webapp/WEB-INF/views/admin/adminagency.jsp, src/main/webapp/WEB-INF/views/admin/adminagencynav.jsp
=> 관리자 기획사관리 기능 완료

src/main/java/com/jcticket/user/controller/SignUpController.java
=> 회원가입 valid 적용

src/main/java/com/jcticket/user/controller/LoginController.java, src/main/java/com/jcticket/user/controller/SignUpController.java, src/main/java/com/jcticket/user/service/UserServiceImpl.java, src/main/webapp/WEB-INF/views/signup/signup.jsp, src/main/webapp/resources/css/signup/signup.css, src/main/webapp/resources/js/signup/signup.js, src/test/java/com/jcticket/user/service/UserServiceImplTest.java
=> 회원가입,로그인 valid

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/admin/dto/AdminDto.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/webapp/WEB-INF/views/admin/adminsetting.jsp, src/main/webapp/WEB-INF/views/admin/common/adminsettingnav.jsp
=> 관리자 정보 수정 기능 완료

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/admin/dto/CouponDto.java, src/main/java/com/jcticket/admin/dto/PageDto.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/webapp/WEB-INF/views/admin/admincoupon.jsp, src/main/webapp/WEB-INF/views/admin/admincoupondelete.jsp, src/main/webapp/WEB-INF/views/admin/admincouponregister.jsp, src/main/webapp/WEB-INF/views/admin/common/admincouponnav.jsp, src/main/webapp/resources/js/admin/admin.js, src/test/java/com/jcticket/admin/dao/AdminDaoImplTest.java
=> 관리자 쿠폰 기능 구현 완료

src/main/webapp/WEB-INF/spring/root-context.xml
=> root-context 복구

.idea/webContexts.xml, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/webapp/WEB-INF/views/admin/adminproductregister.jsp, src/main/webapp/WEB-INF/views/notice/notice.jsp, src/main/webapp/resources/css/admin/admin.css, src/main/webapp/resources/css/notice/notice.css, src/main/webapp/resources/js/admin/admin.js
=> 공연장 공연 정보 팝업 레이아웃 기능

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/webapp/WEB-INF/views/admin/adminproductregister.jsp, src/main/webapp/resources/js/admin/admin.js, src/test/java/com/jcticket/admin/dao/AdminDaoImplTest.java
=> 공연장 공연 정보 팝업 기능 완료

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/java/com/jcticket/viewdetail/dto/ShowingDto.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/webapp/WEB-INF/views/admin/adminproductregister.jsp, src/main/webapp/resources/js/admin/admin.js, src/test/java/com/jcticket/viewdetail/dao/ViewDetailDaoTest.java
=> 회차 등록 기능 구현 완료

src/main/java/com/jcticket/admin/service/AdminServiceImpl.java
=> 공연 파일경로 오류 수정

src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/resources/css/components/index.css, src/main/webapp/resources/js/index/top_slide.js
=> 메인페이지 dday

src/main/webapp/WEB-INF/views/agency/agencydashboard.jsp
=> 기획사 로그인 성공화면 수정

src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/webapp/WEB-INF/views/admin/adminproduct.jsp, src/main/webapp/WEB-INF/views/admin/adminproductmodify.jsp, src/test/java/com/jcticket/admin/dao/AdminDaoImplTest.java
=> 상품 관리 레이아웃 기능 완료

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/admin/adminproduct.jsp, src/main/webapp/WEB-INF/views/admin/common/adminheader.jsp, src/test/java/com/jcticket/admin/dao/AdminDaoImplTest.java
코드 리펙토링, 상품관리 조건절 수정, 테스트케이스 오류 수정
=> 코드 리펙토링, 상품관리 조건절 수정

src/main/java/com/jcticket/user/controller/LoginController.java, src/main/java/com/jcticket/user/controller/SignUpController.java, src/main/java/com/jcticket/user/sns/KakaoLoginApi.java, src/main/java/com/jcticket/user/sns/KakaoLoginBO.java, src/main/webapp/WEB-INF/views/login/login.jsp, src/main/webapp/WEB-INF/views/signup/signupSNS.jsp
=> 카카오 로그인 구현완료

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/admin/dto/PageDto.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/webapp/WEB-INF/views/admin/admincoupon.jsp, src/main/webapp/WEB-INF/views/admin/adminproduct.jsp, src/main/webapp/resources/js/admin/admin.js
=> 상품관리 페이징, 삭제기능 완료

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/admin/dao/AdminDao.java, src/main/java/com/jcticket/admin/dao/AdminDaoImpl.java, src/main/java/com/jcticket/admin/dto/PlayDto.java, src/main/java/com/jcticket/admin/service/AdminService.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/webapp/WEB-INF/views/admin/admindashboard.jsp, src/main/webapp/WEB-INF/views/admin/adminproduct.jsp, src/main/webapp/WEB-INF/views/admin/adminproductmodify.jsp, src/main/webapp/WEB-INF/views/admin/adminproductregister.jsp, src/main/webapp/WEB-INF/views/admin/common/adminheader.jsp, src/main/webapp/resources/js/admin/admin.js, src/test/java/com/jcticket/viewdetail/dao/ViewDetailDaoTest.java
관리자 상품관리 수정 기능 추가, 대시보드 기능 수정, 관리자 세션 초 단위 JS 기능 추가, 관리자 회원 등록 비밀번호 암호화 추가
=> 관리자 상품관리 수정 기능 추가, 대시보드 기능 수정, 관리자 세션 초 단위 JS 기능 추가, 관리자 회원 등록 비밀번호 암호화 추가

src/test/java/com/jcticket/admin/dao/AdminDaoImplTest.java
=> AdminDaoImplTest 테스트케이스 수정

.idea/misc.xml, src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/admin/admindashboard.jsp, src/main/webapp/WEB-INF/views/admin/adminnoticedelete.jsp, src/main/webapp/WEB-INF/views/admin/adminproduct.jsp, src/main/webapp/WEB-INF/views/admin/adminuserdelete.jsp, src/main/webapp/WEB-INF/views/admin/adminuserregister.jsp, src/main/webapp/resources/js/admin/admin.js
회원가입 장르 select, 삭제 코드 중복, 쿠폰 등록 순서 조건절 수정 오류 수정
=> 회원가입 장르 select, 삭제 코드 중복, 쿠폰 등록 순서 조건절 수정 오류 수정

src/main/java/com/jcticket/filter/loginCheckFilter.java
=> 관리자단 Filter 기능 추가

src/main/java/com/jcticket/filter/AdminCheckFilter.java, src/main/java/com/jcticket/filter/UserCheckFilter.java, src/main/webapp/WEB-INF/spring/root-context.xml
=> 관리자 로그인 필터 제외 로직 추가

.idea/misc.xml, src/main/java/com/my/HomeController.java, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/resources/js/index/top_slide.js
=> 메인페이지 이미지 넣기

src/main/java/com/jcticket/ticketing/dto/CouponResponseDto.java, src/main/java/com/jcticket/ticketing/service/TicketingServiceImpl.java, src/main/resources/mybatis/mapper/ticketing/ticketingMapper.xml, src/main/webapp/WEB-INF/views/ticketing/booking.jsp, src/main/webapp/resources/css/ticketing/booking.css, src/main/webapp/resources/js/ticketing/booking.js, src/test/java/com/jcticket/ticketing/service/TicketingServiceImplTest.java
=> update: 쿠폰선택 view, js 구현완료

src/test/java/com/jcticket/admin/dao/AdminDaoImplTest.java
=> AdminDaoImplTest 충돌 삭제

src/main/java/com/jcticket/dto/UserCouponDto.java, src/main/java/com/jcticket/mypage/controller/mypageController.java, src/main/java/com/jcticket/mypage/dto/UserCouponDto.java, src/main/java/com/jcticket/ticketing/dao/TicketingDao.java, src/main/java/com/jcticket/ticketing/dao/TicketingDaoImpl.java, src/main/java/com/jcticket/ticketing/service/TicketingServiceImpl.java, src/main/resources/mybatis/mybatis-config.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/test/java/com/jcticket/ticketing/dao/TicketingDaoImplTest.java
UserCouponDto mypage 경로 수정변경으로 인한 에러 수정
=> UserCouponDto mypage 경로 수정변경으로 인한 에러 수정

src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/viewdetail/viewdetail.jsp, src/main/webapp/resources/css/viewdetail/viewdetail.css, src/main/webapp/resources/js/viewdetail/viewdetail.js
=> url경로 및 리뷰 css완료

src/main/webapp/WEB-INF/views/common/footer.jsp, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/common/search.jsp, src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/WEB-INF/views/signup/signup.jsp, src/main/webapp/resources/js/signup/signup.js
header,footer,search,index,signup jsp파일, 자바스크립트파일 contextPath붙이는거 완료
=> header,footer,search,index,signup jsp파일, 자바스크립트파일 contextPath붙이는거

src/main/java/com/jcticket/admin/dto/PlayDto.java, src/main/java/com/jcticket/admin/dto/PlayImgDto.java, src/main/java/com/jcticket/admin/service/AdminServiceImpl.java, src/main/resources/mybatis/mapper/admin/adminMapper.xml, src/main/resources/mybatis/mapper/user/userMapper.xml, src/main/webapp/WEB-INF/views/admin/adminproductregister.jsp, src/main/webapp/WEB-INF/views/category/musical.jsp, src/main/webapp/WEB-INF/views/index.jsp
=> 메인페이지 슬라이드 이미지 업로드

src/main/webapp/WEB-INF/views/index.jsp
=> 메인페이지 슬라이드 클릭안되게

src/main/webapp/WEB-INF/views/mypage/modify.jsp, src/main/webapp/WEB-INF/views/mypage/mypage_client.jsp, src/main/webapp/WEB-INF/views/mypage/mypage_cupon.jsp, src/main/webapp/WEB-INF/views/mypage/mypage_detail.jsp, src/main/webapp/WEB-INF/views/mypage/mypage_main.jsp, src/main/webapp/WEB-INF/views/mypage/mypage_ticket.jsp, src/main/webapp/WEB-INF/views/mypage/mypage_view.jsp, src/main/webapp/WEB-INF/views/mypage/withdraw.jsp
=> ${pageContext.request.contextPath} 붙힌 거

.idea/dataSources.xml, src/main/java/com/jcticket/viewdetail/controller/ViewController.java, src/main/resources/mybatis/mapper/viewdetail/viewdetailMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/viewdetail/viewdetail.jsp, src/main/webapp/resources/js/viewdetail/viewdetail.js
=> 상세보기 후기삭제 수정

src/main/java/com/jcticket/payment/controller/PaymentController.java, src/main/java/com/jcticket/payment/dto/PaymentRequestDto.java, src/main/java/com/jcticket/payment/service/PaymentService.java, src/main/java/com/jcticket/payment/service/PaymentServiceImpl.java, src/main/webapp/WEB-INF/views/ticketing/booking.jsp, src/main/webapp/resources/js/ticketing/booking.js
=> update: 결제 서비스 코드 에러 해결

src/main/java/com/jcticket/dto/UserCouponDto.java, src/main/java/com/jcticket/payment/service/PaymentServiceImpl.java
=> 결재시 쿠폰 에러 해결

src/main/java/com/jcticket/user/controller/SignUpController.java, src/main/resources/mybatis/mapper/mypage/mypageMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml
mypage 오류 수정, 회원가입 후 index 페이지 이동
=> mypage 오류 수정, 회원가입 후 index 페이지 이동

src/main/resources/mybatis/mapper/viewdetail/viewdetailMapper.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/viewdetail/viewdetail.jsp, src/main/webapp/resources/js/viewdetail/viewdetail.js
=> review 수정사항 반영

src/main/java/com/jcticket/admin/controller/AdminController.java, src/main/java/com/jcticket/notice/controller/NoticeController.java, src/main/java/com/jcticket/notice/dto/NoticeDto.java, src/test/java/com/jcticket/notice/dao/NoticeDaoImplTest.java, src/test/java/com/jcticket/notice/service/NoticeServiceImplTest.java
=>  공지사항 테스트케이스 코드 리팩토링

pom.xml, src/main/java/com/jcticket/ticketing/dto/TicketingDto.java, src/main/webapp/WEB-INF/views/viewdetail/viewdetail.jsp, src/main/webapp/resources/js/viewdetail/viewdetail.js, src/test/java/com/jcticket/mypage/dao/mypageDAOTest.java
=> 운영 경로 오류 수정

src/main/java/com/jcticket/user/controller/SignUpController.java, src/main/java/com/jcticket/user/service/UserService.java, src/main/java/com/jcticket/user/service/UserServiceImpl.java, src/main/resources/mybatis/mapper/user/userMapper.xml
=> signup컨트롤러 리펙토링
